Name=input("enter your name:")
Age=int(input("enter your age:"))
College=input("enter your collage name:")
Branch=input("enter your branch:")
Semester=int(input("enter your semester:"))
marks=float(input("enter your marks:"))
print("\n==== STUDENT INFORMATION====")
print("Name:",Name)
print("Age:",Age)
print("College:",College)
print("Branch:",Branch)
print("semester:",Semester)
print("python:",marks)